import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcVersions
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
object Libs {
    const val appcompat: String = "androidx.appcompat:appcompat:_"

    const val browser: String = "androidx.browser:browser:_"

    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:_"

    const val databinding_adapters: String = "androidx.databinding:databinding-adapters:_"

    const val databinding_common: String = "androidx.databinding:databinding-common:_"

    const val databinding_compiler: String = "androidx.databinding:databinding-compiler:_"

    const val databinding_runtime: String = "androidx.databinding:databinding-runtime:_"

    const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:_"

    const val lifecycle_viewmodel: String = "androidx.lifecycle:lifecycle-viewmodel:_"

    const val multidex: String = "androidx.multidex:multidex:_"

    const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    const val androidx_test_runner: String = "androidx.test:runner:_"

    const val aapt2: String = "com.android.tools.build:aapt2:_"

    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:_"

    const val exoplayer_core: String = "com.google.android.exoplayer:exoplayer-core:_"

    const val exoplayer_hls: String = "com.google.android.exoplayer:exoplayer-hls:_"

    const val exoplayer_ui: String = "com.google.android.exoplayer:exoplayer-ui:_"

    const val extension_mediasession: String =
            "com.google.android.exoplayer:extension-mediasession:_"

    const val gson: String = "com.google.code.gson:gson:_"

    const val firebase_messaging: String = "com.google.firebase:firebase-messaging:_"

    const val google_services: String = "com.google.gms:google-services:_"

    const val push_notifications_android: String = "com.pusher:push-notifications-android:_"

    const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    const val io_gitlab_arturbosch_detekt_gradle_plugin: String =
            "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:_"

    const val junit: String = "junit:junit:_"

    const val eventbus: String = "org.greenrobot:eventbus:_"

    const val eventbus_annotation_processor: String =
            "org.greenrobot:eventbus-annotation-processor:_"

    const val kotlin_android_extensions: String = "org.jetbrains.kotlin:kotlin-android-extensions:_"

    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:_"

    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:_"

    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:_"

    const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"
}
