import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val appcompat: String = "1.0.2"

    const val browser: String = "1.0.0"

    const val constraintlayout: String = "1.1.3"

    const val androidx_databinding: String = "3.5.0"

    const val androidx_lifecycle: String = "2.0.0"

    const val espresso_core: String = "3.2.0"

    const val androidx_test_runner: String = "1.2.0"

    const val aapt2: String = "3.5.0-5435860"

    const val com_android_tools_build_gradle: String = "3.5.0"

    const val lint_gradle: String = "26.5.0"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val junit: String = "4.12"

    const val org_jetbrains_kotlin: String = "1.3.50"

    const val io_gitlab_arturbosch_detekt: String = "1.1.1"

    /**
     *
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "5.6.2"

    const val gradleCurrentVersion: String = "5.6.2"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)

val PluginDependenciesSpec.detekt: PluginDependencySpec
    inline get() =
        id("io.gitlab.arturbosch.detekt").version(Versions.io_gitlab_arturbosch_detekt)
